- pydemo:
  - datum:
    - textio.md
    - dataview.md
    - geogrids.md
    - ssitems.md
  - scicomp:
    - stats.md
    - optimize.md
    - mlearn.md
    - special.md
    - numerics.md
  - porepy:
    - fluidflow.md
    - geomech.md
    - emfields.md
    - geomodel.md
- engineering:
  - resources:
    - susenergy.md
    - transport.md
  - formeval:
    - geology.md
    - resfluids.md
    - geophysics.md
    - petrophysics.md
    - wlogging.md
    - wtesting.md
  - upstream:
    - drilling.md 
    - completion.md 
    - production.md
    - reservoir.md
    - geomechanics.md
    - naturalgas.md
    - eor.md
  - manage:
    - legislation.md
    - pvaluation.md
    - engethics.md
- modeling:
  - python:
    - essentials.md
    - packages.md
  - scicomp:
    - stats.md
    - optimize.md
    - mlearn.md
    - special.md
    - numerics.md
  - fluidflow:
    - fluidmech.md
    - blackoil.md
    - fracmed.md
  - geomech:
    - geomech.md
    - wstab.md
    - sandprod.md
    - hfprop.md
  - emfields:
    - emcomp.md
    - reslog.md
  - geomodel:
    - geostats.md
- application:
  - 2021-2022:
    - htr.md
- contribution:
  - author:
    - jshiriyev.md